baseURL = 'https://rodrigolrgh.github.io/Portafolio_ParadigmasProgramacion/'
languageCode = 'en-us'
title = 'Rodrigo López Rojas'
theme = 'anake'

[pagination]
  pagerSize = 5

[params]
  author = "Rodrigo López Rojas"
